import type { Metadata } from "next";
import React from "react";
import "../../public/styles/normalize.css";
import "@/styles/global.scss"
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
